# Generated by Django 4.2 on 2025-06-05 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
    ]
