# Generated by Django 4.2 on 2025-06-05 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال')], default='zarinpal', max_length=100)),
                ('pay_local_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('authority', models.CharField(editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('successful', 'موفق'), ('failed', 'ناموفق'), ('refunded', 'مسترد شده')], default='pending', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
