# Generated by Django 4.2 on 2025-06-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
